language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

global:
  - CI=true
  - CI_ENVIRONMENT=testing

# Recommended by Travis support
sudo: required
dist: xenial
group: edge

env:
  - DB=mysqli
  - DB=postgres
  - DB=sqlite

services:
  - memcached
  - mysql
  - postgresql
  - redis-server

cache:
  directories:
    - vendor

script:
  - php vendor/bin/phpunit -v

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot;
  - mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test';" -uroot
  - psql -c 'CREATE DATABASE test;' -U postgres
  - sudo apt-get install ghostscript
  - yes | pecl install imagick

before_script:
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then
      git clone -b stable https://github.com/jedisct1/libsodium.git
      cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
      printf "\n" | pecl install -f libsodium
    fi
  - composer install --prefer-source

after_success:
  - travis_retry php tests/bin/php-coveralls.phar -v
